FROM node:18-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy application code
COPY . .

# Set environment variable for the port
ENV PORT=3000

EXPOSE 3000

# Start the application
CMD ["npm", "start"]
