services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/rails
      - bundle_data:/usr/local/bundle
    command: "./bin/rails server -p 3001 -b 0.0.0.0"
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      RAILS_ENV: development
    depends_on:
      - db
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - WDS_SOCKET_PORT=3000
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  playwright:
    image: mcr.microsoft.com/playwright:v1.58.2-noble
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
      - BASE_URL=http://frontend:3000
    command: npx playwright test
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  bundle_data:
