FROM ruby:3.1.2

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

# Set working directory
WORKDIR /rails

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application code
COPY . .

# Ensure bin files are executable
RUN chmod +x bin/* && \
    chmod +x /usr/bin/docker-entrypoint

# Add a script to be executed every time the container starts.
ENTRYPOINT ["docker-entrypoint"]

EXPOSE 3000

# Start the main process.
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
